//"use client";
//import React, { useState } from "react";
import "./globals.css";
import styles from "./style.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { MenuProvider } from "@/context/IngredientsContext";
import bgImage from "@/assets/images/background.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCaretSquareRight,
  faCaretSquareLeft,
  faArrowCircleUp,
} from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [count, setCount] = useState(1);
  // const backgroundClass =
  //   count === 1
  //     ? styles.background1
  //     : count === 2
  //     ? styles.background2
  //     : styles.background3;
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          backgroundImage: `url(${bgImage.src})`,
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
          minHeight: "100vh",
        }}
      >
        <MenuProvider>
          {/* <div className={`${backgroundClass}`}> */}
          <Navigation />
          {/* <div className={styles.container_button}>
              <div className={styles.container_text}>выберите фон</div>
              <div
                className={styles.button}
                onClick={() => setCount(count < 2 ? 1 : count - 1)}
              >
                <FontAwesomeIcon icon={faCaretSquareLeft} />
              </div>
              <div className={styles.button}>{count}</div>
              <div
                className={styles.button}
                onClick={() => setCount(count > 2 ? 3 : count + 1)}
              >
                <FontAwesomeIcon icon={faCaretSquareRight} />
              </div>
            </div> */}
          {children}
          <Footer />
          {/* </div> */}
        </MenuProvider>
      </body>
    </html>
  );
}
